config/routes.rb
Rails.application.routes.draw do

  namespace :api do
    resources :portfolios, :securitys, :users
  end

  root 'static_pages#home'

  get 'sessions/new'

  get 'users/new'

  post '/users/:id', to: 'users#cashTransfer'

  get '/help', to: 'static_pages#help'
  
  get '/about', to: 'static_pages#about'
#When we 'GET' the signup page, we use users#new
  get '/signup', to: 'users#new'

  get '/useragreement', to: 'static_pages#user_agreement'

#When we 'POST' to the signup page (i.e. create new user)
#we use 'users#create'
  post '/signup', to: 'users#create'

  post '/portfolios/new', to: 'portfolios#create'
  get '/portfolios/new', to: 'portfolios#new'

  get '/portfolios/:id', to: 'portfolios#show'

  post '/securitys/:id', to: 'securitys#add_execution'

  get '/executes/index', to: 'executes#index'

  get '/securitys/index', to: 'securitys#index'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users
  resources :account_activation, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :portfolios
  resources :securitys
  resources :executes
end

app/models/security.rb
class Security < ApplicationRecord
	has_many :intradays
	has_many :interdays
end

app/controllers/api/securitys_controller.rb
require 'open3'

class Api::SecuritysController < ApplicationController
	skip_before_action :verify_authenticity_token

	def show
		if !!params[:id]
			security = Security.find(params[:id])

			_ticker = security.ticker
			_name = security.title
			_description = security.description
			_price = security.price
			_expret = security.expreturn
			_stddev = security.stddev
			_last_dividend = security.dividend
			_div_yield = security.divyield
			_num_shares = security.numshares
			_mkt_correlation = security.mktcorr

			_history = security.interdays.order("date ASC")

			_history_week = []
			_history_month = []
			_history_year = []

			



			day7count = 0
			day7date = Time.now

			while day7count <= 5
				if !!Security.find(params[:id]).interdays.find_by(date: ((day7date.to_s).split)[0])
					_value_open = Security.find(params[:id]).interdays.find_by(date: ((day7date.to_s).split)[0]).open
					_history_week.push({date: ((day7date.to_s).split)[0], price: _value_open})
					_value = Security.find(params[:id]).interdays.find_by(date: ((day7date.to_s).split)[0]).close
					_history_week.push({date: ((day7date.to_s).split)[0], price: _value})
					day7count += 1
				end
				day7date -= 1.day
			end

			day30count = 0
			day30date = Time.now

			while day30count <= 22
				if !!Security.find(params[:id]).interdays.find_by(date: ((day30date.to_s).split)[0])
					_value = Security.find(params[:id]).interdays.find_by(date: ((day30date.to_s).split)[0]).close
					_history_month.push({date: ((day30date.to_s).split)[0], price: _value})
					day30count += 1
				end
				day30date -= 1.day
			end

			day365count = 0
			day365date = Time.now

			while day365count <= 260
				if !!Security.find(params[:id]).interdays.find_by(date: ((day365date.to_s).split)[0])
					_value = Security.find(params[:id]).interdays.find_by(date: ((day365date.to_s).split)[0]).close
					_history_year.push({date: ((day365date.to_s).split)[0], price: _value})
					day365count += 5
				else
					day365date -= 1.day
				end
				day365date -= 7.days
			end

			all_intraday_values = []
			cardinal_index = 0
			cardinal_indexables = 0

			security.intradays.each do |intraday|
				if intraday.updated
					cardinal_indexables += 1
				end

				t = Time.parse("10:00") + intraday.cardinal360 * 60

				this_time = (((t).to_s).split)[1]

				if intraday.updated

					all_intraday_values.push(
						{
							date: this_time,
							price: intraday.price
						}
					)

				end
			end

			if !(all_intraday_values.length>0)
				all_intraday_values.push(
					date: "Last close",
					price: security.intradays.find_by(cardinal360: 360).price
				)
				all_intraday_values.push(
					date: "Today",
					price: security.intradays.find_by(cardinal360: 360).price
				)
			end

			#_history_day = []

			#if all_intraday_values.length < 30
			#	_history_day = all_intraday_values
			#else

			#end

			render json: {
				ticker: _ticker,
				name: _name,
				description: _description,
				price: _price,
				expret: _expret,
				stddev: _stddev,
				lastDividend: _last_dividend,
				divYield: _div_yield,
				numShares: _num_shares,
				mktCorrelation: _mkt_correlation,
				historyDay: all_intraday_values,
				historyWeek: _history_week,
				historyMonth: _history_month,
				historyYear: _history_year
			}.to_json
		end
	end
end

app/controllers/securitys_controller.rb
class SecuritysController < ApplicationController

	def show
		
		@security = Security.find(params[:id])
	end

	def index
		
	end

	def add_execution
		@security = Security.find(params[:id])
		_pf_id = params[:buySell][:portfolio].to_i
		_value = params[:buySell][:value].to_f

		_approved = false

		current_user.portfolios.each do |portfolio|
			if (_pf_id == portfolio.id)
				_approved = true
				puts("X1")
			end
		end

		_has_asset = false

		current_user.portfolios.each do |portfolio|
			portfolio.assets.each do |asset|
				if (asset.sec == @security.id)
					_has_asset = true
					puts("X2")
				end
			end
		end
		#ISSUES! :O
		if (_approved)
			Portfolio.find(_pf_id).executes.create(securityID: @security.id, timeblock: 100, volume: (_value/@security.price)/1.001, status: 1)
		end
		redirect_to root_url
	end

end

app/helpers/securitys_helper.rb
module SecuritysHelper
	def big_num_string(value, rounding)
		if (value<1000)
			return value.round(rounding).to_s
		elsif (value<1000000)
			return ((value/1000).round(rounding).to_s) + "K"
		elsif (value<1000000000)
			return ((value/1000000).round(rounding).to_s) + "M"
		else
			return ((value)/1000000000).round(rounding).to_s + "B"
		end
	end

	def user_own_security(security)
		_own = 0.0
		current_user.portfolios.each do |portfolio|
			portfolio.assets.each do |asset|
				if (asset.sec == @security.id)
					_own += security.price * asset.volume
				end
			end
		end

		if (_own < 0.01)
			return "$0"
		else
			return number_to_currency(_own)
		end

	end

	def change_last_close(security)
		_price_now = security.price

		_date = Time.now

		while !security.interdays.find_by(date: ((_date.to_s).split)[0])
			_date = _date - 1.day
		end

		return _price_now - security.interdays.find_by(date: ((_date.to_s).split)[0]).close

	end

	def change_last_week(security)
		_price_now = security.price

		_date = Time.now - 7.days

		while !security.interdays.find_by(date: ((_date.to_s).split)[0])
			_date = _date - 1.day
		end

		return _price_now - security.interdays.find_by(date: ((_date.to_s).split)[0]).close
	end

end

app/views/securitys/index.html.erb
<% PriceUpdateJob.perform_later(10.00) %>
<h1>ASX Securities</h1>
<table>
	<tr>
		<td>Ticker</td>
		<td>Security</td>
		<td>Price</td>
		<td>Expected Return (%)</td>
		<td>Std Deviation (Risk)</td>
		<td>Market Cap</td>
	</tr>
	<% Security.all.each do |security| %>
		<tr>
			<td><%= security.ticker %></td>
			<td><%= link_to security.title, security_path(security) %></td>
			<td><%= number_to_currency(security.price) %></td>
			<td><%= (security.expreturn * 100).round(2) %>%</td>
			<td><%= (security.stddev * 100).round(2) %>%</td>
			<% _mkt_cap = (security.numshares * security.price) %>
			<td><%= "$"+big_num_string(_mkt_cap,1) %></td>
		</tr>
	<% end %>
</table>

app/views/securitys/show.html.erb
<h1 id="securityTitle" class="myHeader">
	<span><%= @security.ticker %> </span>
	<%= @security.title %>
</h1>
<div class="row">
	<div class="col-sm-8">
		<canvas id="securityHistory" ></canvas>
		
	</div>
	<div class="col-sm-4" id="securityTopRight">
		<%= react_component('SecurityView', {id: @security.id}) %>
	</div>
</div>

<div class="row" id="securityMidBox">
	<div class="col-sm-3">
		<div>
			<h4>You own</h4>
			<h3><%= user_own_security(@security) %></h3>
			<h4>of this security.</h4>
		</div>
	</div>
	<div class="col-sm-3">
		<div>
			<h4>Change</h4>
			<% _change_last_close = change_last_close(@security) %>
			<h3 
				<% if _change_last_close > 0.0 %>
				class="changeUp"
				<% else %>
				class="changeDown"
				<% end %>
			>
				
				<% if _change_last_close > 0 %>
				<span id="midInfoArrowResize" class="glyphicon glyphicon-arrow-up"></span>
				<%= number_to_currency(_change_last_close) %>
				<%= ((100.0 * _change_last_close / @security.price).round(2)).to_s + '%' %>
				<% else %>
				<span id="midInfoArrowResize" class="glyphicon glyphicon-arrow-down"></span>
				<%= number_to_currency(-1.0*_change_last_close) %>
				<%= ((-100.0 * _change_last_close / @security.price).round(2)).to_s + '%' %>
				<% end %>
			</h3>
			<h4>from last close</h4>
		</div>
	</div>
	<div class="col-sm-3">
		<div>
			<h4>Change</h4>
			<% _change_last_week = change_last_week(@security) %>
			<h3 
				<% if _change_last_week > 0.0 %>
				class="changeUp"
				<% else %>
				class="changeDown"
				<% end %>
			>
				
				<% if _change_last_week > 0 %>
				<span id="midInfoArrowResize" class="glyphicon glyphicon-arrow-up"></span>
				<%= number_to_currency(_change_last_week) %>
				<%= ((100.0 * _change_last_week / @security.price).round(2)).to_s + '%' %>
				<% else %>
				<span id="midInfoArrowResize" class="glyphicon glyphicon-arrow-down"></span>
				<%= number_to_currency(-1.0*_change_last_week) %>
				<%= ((-100.0 * _change_last_week / @security.price).round(2)).to_s + '%' %>
				<% end %>
			</h3>
			<h4>from last week</h4>
		</div>
	</div>
	<div class="col-sm-3">
		<div>
			<h4>Expected return</h4>
			<h3>
				<%= (100.0*@security.expreturn).to_s + '%' %>
			</h3>
			<h4>annual return.</h4>
		</div>
	</div>
</div>

<div class="row" id="securityInfoBox">
	<div class="col-sm-6">
		<div>
			<h3>
				About <%= @security.title %>
			</h3>
			<p>
				<%= @security.description %>
			</p>
		</div>
	</div>
	<div class="col-sm-6">
	</div>
</div>

<!--


<table>
	<tr>
		<td>Expected Return:</td><td><%= @security.expreturn * 100 %>%</td>
	</tr>
	<tr>
		<td>Standard Deviation (risk):</td><td><%= @security.stddev * 100%>%</td>
	</tr>
	<tr>
		<td>Idiosyncratic risk:</td><td><%= @security.idiosync * 100 %>%</td>
	</tr>
	<tr>
		<td>Last dividend:</td><td><%= number_to_currency(@security.dividend) %></td>
	</tr>
	<tr>
		<td>Dividend yield:</td><td><%= 100*@security.divyield %>%</td>
	</tr>
	<tr>
		<td>Market capitalisation:</td><td>$<%= big_num_string(@security.numshares * @security.price,2) %></td>
	</tr>
</table>
<p>
	<%= @security.description %>
</p> -->

<h2>Buy or sell this security.</h2>

<%= form_for(:buySell) do |f| %>
	Select the portfolio to transfer from/to:
	<select name="buySell[portfolio]">
		<option value="">Please select a portfolio.</option>
		<% current_user.portfolios.each do |portfolio| %>
			<option value="<%= portfolio.id %>"><%= portfolio.title %></option>
		<% end %>
	</select><br>
	<%= f.label :value, "Value of transfer: $" %>
	<%= f.text_field :value %><br>
	<span>Note: Prices may change before execution.</span>
	<%= f.submit "Submit", class: "btn btn-primary" %>
<% end %>