config/routes.rb
Rails.application.routes.draw do

  namespace :api do
    resources :portfolios, :securitys, :users
  end

  root 'static_pages#home'

  get 'sessions/new'

  get 'users/new'

  post '/users/:id', to: 'users#cashTransfer'

  get '/help', to: 'static_pages#help'
  
  get '/about', to: 'static_pages#about'
#When we 'GET' the signup page, we use users#new
  get '/signup', to: 'users#new'

  get '/useragreement', to: 'static_pages#user_agreement'

#When we 'POST' to the signup page (i.e. create new user)
#we use 'users#create'
  post '/signup', to: 'users#create'

  post '/portfolios/new', to: 'portfolios#create'
  get '/portfolios/new', to: 'portfolios#new'

  get '/portfolios/:id', to: 'portfolios#show'

  post '/securitys/:id', to: 'securitys#add_execution'

  get '/executes/index', to: 'executes#index'

  get '/securitys/index', to: 'securitys#index'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users
  resources :account_activation, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :portfolios
  resources :securitys
  resources :executes
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
	before_action :get_user, only: [:edit, :update]
	before_action :valid_user, only: [:user, :update]
	before_action :check_expiration, only: [:edit, :update]

	def new
	end

	def create
		@user = User.find_by(email: params[:password_reset][:email].downcase)
		if @user
			@user.create_reset_digest
			@user.send_password_reset_email
			redirect_to root_url
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if params[:user][:password].empty?
			@user.errors.add(:password, "can't be empty")
			render 'edit'
		elsif @user.update_attributed(user_params)
			log_in @user
			redirect_to @user
		else
			render 'edit'
		end
	end
			

	private

		def user_params
			params.require(:user).permit(:password, :password_confirmation)
		end

		def get_user
			@user = User.find_by(email: params[:email])
		end

		def valid_user
			unless (@user && @user.activated? &&
				@user.authenticated?(:reset, params[:id]))
			redirect_to root_url
			end
		end

		def check_expiration
			if @user.password_reset_expired?
				redirect_to new_password_reset_url
			end
		end

end

app/views/password_resets/edit.html.erb
<h1>Reset password</h1>
	<%= form_for(@user, url: password_reset_path(params[:id])) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= hidden_field_tag :email, @user.email %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Update password", class: "btn btn-primary" %>
    <% end %>

app/views/password_resets/new.html.erb
<div id="forgotPasswordSquare">
	<h1 class="myHeader">Forgot password</h1>
	<p>
		Enter your email, and we will reset your password via email.
	</p>
	<%= form_for(:password_reset, url: password_resets_path) do |f| %>
		<%= f.label :email %>
		<%= f.email_field :email, class: 'form-control' %>
		<br>
		<%= f.submit "Submit", class: "myButton" %>
	<% end %>
	<p>
		<b>Not working or can't remember your email?</b>
		<%= link_to "Contact Us", about_path %>
	</p>
</div>