config/routes.rb
Rails.application.routes.draw do

  namespace :api do
    resources :portfolios, :securitys, :users
  end

  root 'static_pages#home'

  get 'sessions/new'

  get 'users/new'

  post '/users/:id', to: 'users#cashTransfer'

  get '/help', to: 'static_pages#help'
  
  get '/about', to: 'static_pages#about'
#When we 'GET' the signup page, we use users#new
  get '/signup', to: 'users#new'

  get '/useragreement', to: 'static_pages#user_agreement'

#When we 'POST' to the signup page (i.e. create new user)
#we use 'users#create'
  post '/signup', to: 'users#create'

  post '/portfolios/new', to: 'portfolios#create'
  get '/portfolios/new', to: 'portfolios#new'

  get '/portfolios/:id', to: 'portfolios#show'

  post '/securitys/:id', to: 'securitys#add_execution'

  get '/executes/index', to: 'executes#index'

  get '/securitys/index', to: 'securitys#index'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users
  resources :account_activation, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :portfolios
  resources :securitys
  resources :executes
end

app/models/user.rb
class User < ApplicationRecord
	has_many :portfolios, dependent: :destroy
	attr_accessor :remember_token, :activation_token
	before_save { self.email = email.downcase }
	before_create :create_activation_digest

	validates :name, presence: true, length: { maximum: 50 }

	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, length: { maximum: 255 },
					format: { with: VALID_EMAIL_REGEX },
					uniqueness: { case_sensitive: false }

	has_secure_password

	validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

	# Digest method for use in fixtures.
	def User.digest(string)
		cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST:
			BCrypt::Engine.cost
		BCrypt::Password.create(string, cost: cost)
	end

	def User.new_token
		SecureRandom.urlsafe_base64
	end

	def authenticated?(attribute, token)
    	digest = send("#{attribute}_digest")
    	return false if digest.nil?
    	BCrypt::Password.new(digest).is_password?(token)
  	end

  	def activate
  		update_attribute(:activated, true)
  		update_attribute(:activated_at, Time.zone.now)
  	end

  	def send_activation_email
  		UserMailer.account_activation(self).deliver_now
  	end

  	def create_reset_digest
  		self.reset_token = User.new_token
  		update_attribute(:reset_digest, User.digest(reset_token))
  		update_attribute(:reset_sent_at, Time.zone.now)
  	end

  	def send_password_reset_email
  		UserMailer.password_reset(self).deliver_now
  	end

  	def password_reset_expired?
  		reset_send_at < 2.hours.ago
  	end

	private

	def create_activation_digest
		self.activation_token = User.new_token
		self.activation_digest = User.digest(activation_token)
	end
end

app/controllers/api/users_controller.rb
class Api::UsersController < ApplicationController
	skip_before_action :verify_authenticity_token
	def show
		@user = User.find(params[:id])

		_securities = []
		_used_tickers = []

		@user.portfolios.each do |portfolio|

			portfolio.assets.each do |asset|
				if !!(_used_tickers.include?(Security.find(asset.sec).ticker))
					_securities.each do |security|
						if security[:ticker] == Security.find(asset.sec).ticker
							security[:volume] += asset.volume
						end
					end
				else
					_securities.push(
						{
							ticker: Security.find(asset.sec).ticker,
							name: Security.find(asset.sec).title,
							price: Security.find(asset.sec).price,
							volume: asset.volume
						}
					)
					_used_tickers.push(Security.find(asset.sec).ticker)
				end
			end

		end

		historical_values = user_value_hist(_securities, @user)
		_user_value = user_value(@user)

		render json: {
			value: _user_value,
			cash: @user.balanceAUD,
			historyWeek: historical_values[:historyWeek],
			historyMonth: historical_values[:historyMonth],
			historyYear: historical_values[:historyYear],
			expRet: user_exp_ret(_securities, _user_value),
			stdDev: 0.40,
			mktCorr: 0.45
		}.to_json
	end

	def update
		if !!params[:id] && !!params[:type] && params[:type] == "cashTransfer"
			
			
			good_request = !!params[:data][:value] && !!params[:data][:portfolioName] && !!User.find(params[:id]).portfolios.find_by(title: params[:data][:portfolioName])
			
			if good_request
				puts "THIS IS GOOD at least"
			end

			user = User.find(params[:id])
			portfolio = user.portfolios.find_by(title: params[:data][:portfolioName])

			if good_request

				#transfer_data = params[:data]
				transfer_value = (params[:data][:value].to_s).to_f
				if transfer_value > 0 #deposit account->PF
					if transfer_value > user.balanceAUD
						render json: {
							status: 401,
							error: "Insufficient account funds to process request."
						}
					else
						user.update_attributes(balanceAUD: user.balanceAUD - transfer_value)
						portfolio.update_attributes(cashAUD: portfolio.cashAUD + transfer_value)
						render json: {
							status: 200
						}
					end
				else
					if transfer_value > portfolio.cashAUD
						render json: {
							status: 401,
							error: "Insufficient portfolio funds to process request."
						}
					else
						user.update_attributes(balanceAUD: user.balanceAUD - transfer_value)
						portfolio.update_attributes(cashAUD: portfolio.cashAUD + transfer_value)
						render json: {
							status: 200
						}
					end
				end
			else
				render json: {
					status: 401,
					error: "Unspecified"
				}
			end
		end
	end

	private

		def user_value(user)
			_value = user.balanceAUD

			user.portfolios.each do |portfolio|

				portfolio.assets.each do |asset|
					_value += asset.volume * Security.find(asset.sec).price
				end

				_value += portfolio.cashAUD

			end

			return _value
		end

		def user_exp_ret(securities, _user_value)

			_weight = 0.0

			securities.each do |security|
				_weight += security[:volume] * security[:price] * Security.find_by(ticker: security[:ticker]).expreturn
			end

			_weight /= _user_value

			return _weight
		end

		def user_value_hist(securities, user)

			_history_week = []

			day7count = 0
			day7date = Time.now

			while day7count <= 5

				add_it = true

				securities.each do |security|
					if !Security.find_by(ticker: security[:ticker]).interdays.find_by(date: ((day7date.to_s).split)[0])
						add_it = false
						day7date -= 1.day
						break
					end
				end

				if add_it

					_value = 0.0

					securities.each do |security|
						puts "here1"
						_value += Security.find_by(ticker: security[:ticker]).interdays.find_by(date: ((day7date.to_s).split)[0]).close * security[:volume]
					end

					#Will have to do CA$H differently
					user.portfolios.each do |portfolio|
						_value += portfolio.cashAUD
					end
					_value += user.balanceAUD

					_history_week.push({date: ((day7date.to_s).split)[0], value: _value})

					day7count += 1
					day7date -= 1.day

				end

			end

			_history_month = []

			day30count = 0
			day30date = Time.now

			while day30count <= 22

				add_it = true

				securities.each do |security|
					if !Security.find_by(ticker: security[:ticker]).interdays.find_by(date: ((day30date.to_s).split)[0])
						add_it = false
						day30date -= 1.day
						break
					end
				end

				if add_it

					_value = 0.0

					securities.each do |security|
						puts "here2"
						_value += Security.find_by(ticker: security[:ticker]).interdays.find_by(date: ((day30date.to_s).split)[0]).close * security[:volume]
					end

					#Will have to do CA$H differently
					user.portfolios.each do |portfolio|
						_value += portfolio.cashAUD
					end
					_value += user.balanceAUD

					_history_month.push({date: ((day30date.to_s).split)[0], value: _value})

					day30count += 1
					day30date -= 1.day

				end

			end

			_history_year = []

			day365count = 0
			day365date = Time.now

			while day365count <= 52

				add_it = true

				securities.each do |security|
					if !Security.find_by(ticker: security[:ticker]).interdays.find_by(date: ((day365date.to_s).split)[0])
						add_it = false
						day365date -= 1.day
						break
					end

				end

				if add_it

					_value = 0.0

					securities.each do |security|
						puts "here3"
						_value += Security.find_by(ticker: security[:ticker]).interdays.find_by(date: ((day365date.to_s).split)[0]).close * security[:volume]
					end

					#Will have to do CA$H differently
					user.portfolios.each do |portfolio|
						_value += portfolio.cashAUD
					end
					_value += user.balanceAUD

					_history_year.push({date: ((day365date.to_s).split)[0], value: _value})

					day365count += 1
					day365date -= 7.days

				end

			end

			return {
				historyWeek: _history_week,
				historyMonth: _history_month,
				historyYear: _history_year
			};

		end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :logged_in_user, only: [:edit, :update, :destroy]
	before_action :correct_user, only: [:edit, :update]

	def show
    @user = User.find(params[:id])
    if !(logged_in? && current_user?(@user))
      render "static_pages/forbidden", status: 401
    end
	end

  	def new
  		@user = User.new
  	end

  	def create
  		@user = User.new(user_params)
  		if @user.save
  			@user.send_activation_email
  			#This currently logs in the user. To not log in the
  			#user, go to 11.3 or thereabouts.
  			log_in @user
  			#Put the successful FLASH here
  			redirect_to @user
  		else
  			render 'new'
  		end
  	end

  	def edit
  		@user = User.find(params[:id])
  	end

  	def index
  		@users = User.all
  	end

  	def update
  		@user = User.find(params[:id])
  		if @user.update_attributes(user_params)
  			redirect_to @user
  		else
  			render 'edit'
  		end
  	end

  	def destroy
  		User.find(params[:id]).destroy
  		redirect_to users_url
  	end

    def cashTransfer
      @user = User.find(params[:id])

      _pf_id = params[:cashTrans][:portfolio].to_i
      _value = params[:cashTrans][:value].to_f
      _approved = false

      @user.portfolios.each do |portfolio|
        if _pf_id == portfolio.id
          _approved = true
        end
      end

      if (_value > 0 && (@user.balanceAUD - _value < @user.initial_investment * 0.05))
        _approved = false
      end

      if (_approved)
        if (_value > 0 && @user.balanceAUD > _value)
          @user.update_attributes(balanceAUD: @user.balanceAUD - _value)
          Portfolio.find(_pf_id).update_attributes(cashAUD: Portfolio.find(_pf_id).cashAUD + _value)
        elsif (_value < 0 && Portfolio.find(_pf_id).cashAUD >= -1*_value)
          Portfolio.find(_pf_id).update_attributes(cashAUD: Portfolio.find(_pf_id).cashAUD + _value)
          @user.update_attributes(balanceAUD: @user.balanceAUD - _value)
        else
          puts("Insufficient funds error")
        end

      else
        puts("Did not work.")

      end

      redirect_to @user

    end

  	private

  		def user_params
  			params.require(:user).permit(:name, :email, :password, 
  				:password_confirmation)
  		end

  		def logged_in_user
  			unless logged_in?
  				store_location
  				redirect_to login_url
  			end
  		end

  		#Confirms the correct user
  		def correct_user
  			@user= User.find(params[:id])
  			redirect_to(root_url) unless current_user?(@user)
  		end
end

app/helpers/users_helper.rb
module UsersHelper

	def user_value(user)
		_value = user.balanceAUD
		user.portfolios.each do |portfolio|
			_value += portfolio.cashAUD
			portfolio.assets.each do |asset|
				_value += Security.find(asset.sec).price * asset.volume
			end
		end

		return _value
	end

	def portfolio_value(portfolio)
		_value = portfolio.cashAUD

		portfolio.assets.each do |asset|
			_value += Security.find(asset.sec).price * asset.volume
		end

		return _value
	end

	def portfolio_old_value(portfolio, days_ago)

		_value_now = portfolio_value(portfolio)
		_date = Time.now - days_ago.days
		_date_count = 0
		_date_good = false

		while !_date_good

			portfolio.assets.each do |asset|
				security = Security.find(asset.sec)

				if !!security.interdays.find_by(date: _date)
					_date_count += 1
				else
					_date -= 1.day
					break
				end
			end

			if _date_count >= portfolio.assets.count
				_date_good = true
			end

		end

		_value_then = portfolio.cashAUD

		portfolio.assets.each do |asset|
			_value_then += Security.find(asset.sec).interdays.find_by(date: _date).close * asset.volume
		end

		return _value_then

	end
end

app/views/users/edit.html.erb
<%= form_for(@user) do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name, class: 'form-control' %>

	<%= f.label :email %>
	<%= f.email_field :email, class: 'form-control' %>

	<%= f.label :password %>
	<%= f.password_field :password, class: 'form-control' %>

	<%= f.label :password_confirmation, "confirmation" %>
	<%= f.password_field :password_confirmation, class: 'form-control' %>

	<%= f.submit "Save changes", class: "btn btn-primary" %>
<% end %>

app/views/users/index.html.erb
<% if current_user.admin? %>
	<% @users.each do |user| %>
		<%= link_to user.name, user %>
		<% if current_user.admin? && !current_user?(user) %>
			| <%= link_to "delete", user, method: :delete %>
		<% end %>
		<br>
	<% end %>
<% else %>
	<p>Sorry, but you are not authorised to view this.</p>
<% end %>

app/views/users/new.html.erb
<h1>Signup here.</h1>
<div>
	<%= form_for(@user) do |f| %>
		<%= f.label :name %>
		<%= f.text_field :name %><br>

		<%= f.label :email %>
		<%= f.email_field :email %><br>

		<%= f.label :password %>
		<%= f.password_field :password %><br>

		<%= f.label :password_confirmation, "Confirmation" %>
		<%= f.password_field :password_confirmation %><br>

		<%= f.submit "Create my account", class: "btn btn-primary" %>
	<% end %>
</div>

app/views/users/show.html.erb
<!-- SHOWS A USER -->
<% if logged_in? && current_user?(@user) && current_user.activated || current_user.admin %>
	
	<h1 class="myHeader">My Account</h1>
	<div class="row">
		<div class="col-sm-7">
			<canvas id="userHistory" ></canvas>
		</div>
		<div class="col-sm-3">
			<%= react_component('AccountViewTop', {id: @user.id}) %>
		</div>
		<div class="col-sm-1">
			<!-- need to link to messages -->
			<%= link_to(root_path) do %>
				<div class="smallClickBox">
					<span id="accountMessagesLogo" class="glyphicon glyphicon-envelope"></span>
					<h5>Messages</h5>
				</div>
			<% end %>

			<!-- need to link to external transactions -->
			<%= link_to(root_path) do %>
				<div class="smallClickBox">
					<span id="accountMessagesLogo" class="glyphicon glyphicon-transfer"></span>
					<h5>Transfers</h5>
				</div>
			<% end %>
		</div>
		<div class="col-sm-1"></div>
	</div>

	<h2 class="myHeaderBlue">My Portfolios</h2>
	<div class="row">
		<div class="col-sm-7">
			<% @user.portfolios.all.each do |portfolio| %>
				<% _pf_value = portfolio_value(portfolio) %>
				<%= link_to(portfolio) do %>
				<div class="accountPortfolioList">
					<div class="row">
						<div class="col-sm-6">
							<h3>
								<%= portfolio.title %>
							</h3>
							<table>
								<tr>
									<td>
										Portfolio cash
									</td>
									<td><b>
										<%= number_to_currency(portfolio.cashAUD) %>
									</b></td>
								</tr>
								<tr>
									<td>
										Security value
									</td>
									<td><b>

			<%= number_to_currency(_pf_value - portfolio.cashAUD) %>

									</b></td>
								</tr>
							</table>
						</div>
						<div class="col-sm-6">
							<h3>
								<%= number_to_currency(_pf_value) %>
							</h3>
							<table>
								<tr>
									<td>
										Last close
									</td>
									

			<% _last_close_change = _pf_value - portfolio_old_value(portfolio, 1) %>

									<td

				<% if _last_close_change > 0 %>
					class="changeUp"
				<% else %>
					class="changeDown"
				<% end %>

									><b>

			<% if _last_close_change > 0 %>

			<span class="glyphicon glyphicon-arrow-up"></span>

			<% else %>

			<span class="glyphicon glyphicon-arrow-down"></span>

				<% _last_close_change *= -1 %>

			<% end %>

			<%= number_to_currency(_last_close_change) %>

			<%= ' '+((100.0*(_last_close_change/(_pf_value - _last_close_change))).round(2)).to_s + '%' %>

									</b></td>
								</tr>
								<tr>
									<td>
										Last week
									</td>

			<% _last_close_change = _pf_value - portfolio_old_value(portfolio, 7) %>

									<td

				<% if _last_close_change > 0 %>
					class="changeUp"
				<% else %>
					class="changeDown"
				<% end %>

									><b>
			

			<% if _last_close_change > 0 %>

			<span class="glyphicon glyphicon-arrow-up"></span>

			<% else %>

			<span class="glyphicon glyphicon-arrow-down"></span>

				<% _last_close_change *= -1 %>

			<% end %>

			<%= number_to_currency(_last_close_change) %>

			<%= ' '+((100.0*(_last_close_change/(_pf_value - _last_close_change))).round(2)).to_s + '%' %>

									</b></td>
								</tr>
							</table>
						</div>
						
					</div>

				</div>
				<% end %>
				
			<% end %>
			<%= link_to('/portfolios/new') do %>
			<!-- new_portfolios_path -->
				<div class="accountPortfolioList">
					<h3>
						<span class="glyphicon glyphicon-plus"></span>
						Add new portfolio
					</h3>
				</div>
			<% end %>
		</div>
		<% portfolio_list = [] %>
		<% portfolio_cash_list = [] %>
		<% @user.portfolios.each do |portfolio| %>
		<% portfolio_list.push(portfolio.title) %>
		<% portfolio_cash_list.push(portfolio.cashAUD) %>
		<% end %>
		<%= react_component('UserCashTransfer', {
			id: @user.id, 
			portfolioList: portfolio_list, 
			accountCash: @user.balanceAUD, 
			portfolioCashList: portfolio_cash_list }) %>
	</div>

<% elsif logged_in? && current_user?(@user) %>
	Your account is not yet activated. Please see your email account at: 
	<%= @user.email %>
<% else %>
	class3
<% end %>

<!--
<h3>Welcome, <%= (@user.name.split)[0] %>.</h3>
	<h2>Your position</h2>
	Your balance is: <%= number_to_currency(@user.balanceAUD ) %><br><br>
	Your initial investment is: <%= number_to_currency(@user.initial_investment) %><br><br>

	<% $cash = 0.00 %>
	<% @user.portfolios.each do |portfolio| %>
		<% $cash += portfolio.cashAUD %>
	<% end %>

	Your portfolio cash is: <%= number_to_currency($cash) %><br><br>

	<% $value = 0.00 %>
	<% @user.portfolios.each do |portfolio| %>
		<% portfolio.assets.each do |asset| %>
			<% $value += Security.find(asset.sec).price * asset.volume %>
		<% end %>
	<% end %>
	The value of your portfolio assets is: <%= number_to_currency($value) %><br><br>
	<h3><b>Your total value is: <%= number_to_currency($value + $cash + @user.balanceAUD) %></b></h3>
	<% $return = ((($cash + $value + @user.balanceAUD)/@user.initial_investment-1)*100) %>
	Your return so far is: <%= $return.round(2) %>%<br>

	<% $time = (DateTime.now.in_time_zone - @user.created_at)/(365*24*60*60) %>

	<br>

	<h2>Your details</h2>

	Your email is: <%= @user.email %><br>
	Created at: <%= @user.created_at %> <br>
	Updated at: <%= @user.updated_at %>.<br>
	Go to home page: <%= link_to "Home", root_path %><br>
	You have this many portfolios: <%= @user.portfolios.count %><br>
	Change details: <%= link_to "Settings", edit_user_path(current_user) %><br><br>

	<h2>Transfer money to your portfolios</h2>
	<%= form_for(:cashTrans) do |f| %>
		Select the portfolio to transfer from/to:
		<select name="cashTrans[portfolio]">
			<option value="">Please select a portfolio.</option>
			<% @user.portfolios.each do |portfolio| %>
				<option value="<%= portfolio.id %>"><%= portfolio.title %></option>
			<% end %>
		</select><br>
		<%= f.label :value, "Value of transfer: $" %>
		<%= f.text_field :value %><br>
		<%= f.submit "Submit", class: "btn btn-primary" %>
	<% end %>

	<h2>Your portfolios</h2>
	<% $value = 0.0 %>
	<% @user.portfolios.each do |portfolio| %>
		<b><h3><%= link_to portfolio.title, portfolio_path(portfolio) %></h3></b>
		<% portfolio.assets.each do |asset| %>
			<% $value += Security.find(asset.sec).price * asset.volume %>
		<% end %>
		<% $value += portfolio.cashAUD %>
		The total value of this portfolio is: <b><%= number_to_currency($value) %></b>
		<% $value = 0.0 %>
		<br><br><br>
	<% end %>
	<% if current_user.admin %>
		<br>You're currently logged in as admin.
	<% end %>
	<br><%= link_to "Create a new portfolio", new_portfolio_path %></b>
	<br><br>
-->