config/routes.rb
Rails.application.routes.draw do

  namespace :api do
    resources :portfolios, :securitys, :users
  end

  root 'static_pages#home'

  get 'sessions/new'

  get 'users/new'

  post '/users/:id', to: 'users#cashTransfer'

  get '/help', to: 'static_pages#help'
  
  get '/about', to: 'static_pages#about'
#When we 'GET' the signup page, we use users#new
  get '/signup', to: 'users#new'

  get '/useragreement', to: 'static_pages#user_agreement'

#When we 'POST' to the signup page (i.e. create new user)
#we use 'users#create'
  post '/signup', to: 'users#create'

  post '/portfolios/new', to: 'portfolios#create'
  get '/portfolios/new', to: 'portfolios#new'

  get '/portfolios/:id', to: 'portfolios#show'

  post '/securitys/:id', to: 'securitys#add_execution'

  get '/executes/index', to: 'executes#index'

  get '/securitys/index', to: 'securitys#index'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users
  resources :account_activation, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :portfolios
  resources :securitys
  resources :executes
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Markowitz</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>

  <body>
    <header class="navbar navbar-fixed-top navbar-inverse" 

    <% if logged_in? %>
    id="top-navbar"
    <% else %>
    id="top-navbar-loggedout"
    <% end %>
    >
    
      <div class="row" border-style="none">
      	<!--<div class="col-sm-2">
            

            https://image.ibb.co/mYojC6/allocan_logo_2.png

             
        	<img src="https://image.ibb.co/iNCajG/allocan_logo_blue_background_2.png" id="logo">
        </div> -->
        <div class="col-sm-12">
        	<nav>
          		
            <% if logged_in? %>
                <ul class="nav navbar-nav navbar-left" id="nav-right-list">
                    <li id="logo-top-left">
                        
                            <img src="https://image.ibb.co/fgHVJb/allocan_logo_clear_1.png" alt="allocan_logo_clear_1" />
                        
                    </li>
                    <li>
                        <%= link_to(root_path) do %>
                            <span class="glyphicon glyphicon-home" id="topNavbarHomeIcon"></span>
                        <% end %>
                    </li>
                    <li>
                        <div id="loggedInAs">
                            Logged in as</br>
                            <span><%= current_user.name %></span>
                        </div>
                    </li>
                </ul>
            <% end %>

            <% if !logged_in? %>
                <ul class="nav navbar-nav navbar-left" id="nav-right-list">
                    <li id="logo-top-left-logged-out">
                        <%= link_to(root_path) do %>
                            <img src="https://image.ibb.co/fgHVJb/allocan_logo_clear_1.png" alt="allocan_logo_clear_1" />
                        <% end %>
                    </li>
                </ul>

                <ul class="nav navbar-nav navbar-right" id="nav-right-list-loggedout">
                    <%= link_to(login_path) do %>
                        <button class="top-navbar-button">
                            <b>Sign in</b>
                        </button>
                    <% end %>
                    <%= link_to(signup_path) do %>
                        <button class="top-navbar-button">
                            <b>Sign up</b>
                        </button>
                    <% end %>
                </ul>
            <% else %>

                <ul class="nav navbar-nav navbar-right" id="nav-right-list">
                    <li id="topNavbarRightLogout">
                        <%= link_to(logout_path, method: :delete) do %>
                            <span class="glyphicon glyphicon-off" id="topNavbarOffIcon"></span>
                        <% end %>
                    </li>
                </ul>

            <% end %>

                
        	</nav>
        </div>
      </div>
    </header>
	<div class="row">

	<% if logged_in? %>
		<div id="wrapper">

        <!-- Sidebar -->
        <div id="sidebar-wrapper">
            <ul class="sidebar-nav">
                <li class="sidebar-brand" id="top-info">
                	<span id="grey-marker">Position </span>
                	<%= number_to_currency(user_value(current_user)) %>
                </li>
                <li>
                    <%= link_to(user_path(current_user)) do %>
                        <span class="glyphicon glyphicon-user"></span>
                        My Account
                    <% end %>
                </li>
                <li>
                    <%= link_to(root_path) do %>
                        <span class="glyphicon glyphicon-stats"></span>
                        Portfolios
                    <% end %>
                </li>
                <li>
                    <%= link_to(securitys_index_path) do %>
                        <span class="glyphicon glyphicon-list"></span>
                        Securities
                    <% end %>
                </li>
                <li>
                    <a href="#"><span class="glyphicon glyphicon-envelope"></span>Messages</a>
                </li>
                <li>
                    <a href="#"><span class="glyphicon glyphicon-comment"></span>Community</a>
                </li>
                <li>
                    <a href="#"><span class="glyphicon glyphicon-transfer"></span>External Transactions</a>
                </li>
                <li>
                    <%= link_to(help_path) do %>
                        <span class="glyphicon glyphicon-cog"></span>Settings
                    <% end %>
                </li>
                <li>
                    <%= link_to(help_path) do %>
                        <span class="glyphicon glyphicon-info-sign"></span>
                        Help
                    <% end %>
                </li>
            </ul>
        </div>
        <!-- /#sidebar-wrapper -->

        <!-- Page Content -->
        <div id="page-content-wrapper">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">
                        <%= yield %>
                    </div>
                </div>
            </div>
        </div>
        <!-- /#page-content-wrapper -->

    </div>



    <!-- /#wrapper -->
     <!-- Menu Toggle Script -->
    <script>
    $("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
    });
    </script>


	   	<!--<div class="col-sm-2" id="sidebar">
	    	


	    </div>
	    <div class="col-sm-10">
			
	    </div>-->
	</div>

	<% else %>

    <div class="container-fluid">
    	<div class="row">
    		<div class="col-sm-2">
    		</div>
    		<div class="col-sm-10">
    			<%= yield %>
    		</div>
    	</div>
    </div>

    <% end %>

    <div id="footer">
    	<div class="row">
    		<div class="col-sm-2" id="left-footer">
    			<% if !logged_in? %>

    			<div class="col-sm-2" id="left-footer">
	    			<img src="https://preview.ibb.co/ja04em/allocan_logo_NB_1.png" height="45px">
	    			<p>
	    				Copyright 2017 Allocan Financial Services Pty Ltd.
	    			</p>
	    			<p>
	    				All rights reserved.
	    			</p>
	    			<p>
	    				Australian Financial Licence number 732655
	    			</p>
	    		</div>

	    		<% end %>

    		</div>
    		<div class="col-sm-10" 

    		<% if logged_in? %>

    		id="right-footer-loggedin"

    		<% else %>

    		id="right-footer"

    		<% end %>

    		>
    			<h4>
    				Customer Portal
    			</h4>
    			<a href="#">FAQs</a>
                <%= link_to "Customer Agreement", useragreement_path %>
    			<a href="#">Need help?</a>
    			<a href="#">Feedback</a>
    			<a href="#">Urgent assistance</a>
    			<h4>
    				About Us
    			</h4>
    			<a href="#">Allocan Group</a>
    			<a href="#">Financial Licensure</a>
    			<a href="#">Corporate Sustainability</a>
    			<a href="#">Anti-Money Laundering</a>
    			<a href="#">Careers</a>
    			<a href="#">Allocan in the News</a>
    			<h4>
    				Connect With Us
    			</h4>
                <a href="https://www.facebook.com"><i class="fa fa-facebook-square"></i></a>
                <a href="https://www.twitter.com"><i class="fa fa-twitter-square"></i></a>
                <a href="https://www.youtube.com"><i class="fa fa-youtube-square"></i></a>
                <a href="https://google.com"><i class="fa fa-envelope-square"></i></a>

    			<% if logged_in? %>
    			<p>Copyright 2017 Allocan Financial Services Pty Ltd.</p>
                <p>AFS license number 732490.</p>
    			<% end %>
    		</div>
    	</div>
    </div>
  </body>
</html>


<!---


<div class="col-sm-2" id="left-footer">
    			<img src="https://preview.ibb.co/ja04em/allocan_logo_NB_1.png" height="45px">
    			<p>
    				Copyright 2017 Allocan Financial Services Pty Ltd.
    			</p>
    			<p>
    				All rights reserved.
    			</p>
    		</div>

-->